# Generated by Django 3.2.3 on 2021-06-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('variable', models.CharField(max_length=3, unique=True)),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'ingredients',
            },
        ),
    ]
